### ISSUE TITLE
Testing issues and request to add .dockstore.yml

### ISSUE THREAD

**Issue by low-decarie** [AAFC-Bioinfo-AAC/AMF-rDNA-PacBio-amplicon-sequence-analysis-pipeline#1]
To enable dockerstore integration, please add a .dockstore.yml per https://dockstore.org/github-landing-page?entryType=WORKFLOW.

File content should be an edited version of 

```
version: 1.2 # The .dockstore.yml schema version
workflows:
  - subclass: <CWL | WDL | NFL | GALAXY | SMK>
    primaryDescriptorPath: <String>
    testParameterFiles: # <String Array>
      - <String>
      - <String>
    readMePath: <String>
    authors:
      - orcid: <String>
```
